@rooURL = http://localhost:5116
@devURL = https://localhost:7255

GET {{rooURL}}/weatherforecast/
Accept: application/json
###
GET {{rooURL}}/api/book
Accept: application/json
###
GET {{rooURL}}/api/book/5
Accept: application/json
###
POST {{rooURL}}/api/book
Content-Type: application/json
{
  "id": 5,
  "title": "Tamil",
  "author": "Tamilarasi",
  "yearPublished": 2017
}
###
PUT {{rooURL}}/api/book/5
Content-Type: application/json
{
  "id": 5,
  "title": "History",
  "author": "Rosy Miss",
  "yearPublished": 2014
}
###
DELETE {{rooURL}}/api/book/5
Accept: application/json
###
GET {{rooURL}}/api/EmployeeOffboarding/
Accept: application/json
###
POST {{rooURL}}/api/EmployeeOffboarding
Content-Type: application/json
{
  "employeeId": 2,
  "employeeName": "Test2",
  "employeeEmail": "Test2@gmail.com",
  "reasonForExit": "Test2Reason",
  "lastWorkingDay": "2025-12-29"
}
###
GET {{rooURL}}/api/ReportingManager
###
GET {{rooURL}}/api/ReportingManager/1 
###
POST {{rooURL}}/api/ReportingManager
Content-Type : application/json
{
  "documentId": 2,
  "documentName": "Test"
}
###
GET {{rooURL}}/api/Admin